// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiyRdeZilNtXC5yvSSok3XIci6gupyhFk',
    appId: '1:650287500996:web:75bc16a05522f402280391',
    messagingSenderId: '650287500996',
    projectId: 'test-230e1',
    authDomain: 'test-230e1.firebaseapp.com',
    storageBucket: 'test-230e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOUqFZLmp0Tz9k-Yb8Z1Uigvn7JYkCfs',
    appId: '1:650287500996:android:8d6068653c0169a5280391',
    messagingSenderId: '650287500996',
    projectId: 'test-230e1',
    storageBucket: 'test-230e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_kJVAog5QNkBdHS4kz3chDwfMzMHpyY',
    appId: '1:650287500996:ios:d8ea5317cfecfcae280391',
    messagingSenderId: '650287500996',
    projectId: 'test-230e1',
    storageBucket: 'test-230e1.appspot.com',
    iosClientId: '650287500996-o1d129hr9buromt1l2ul98s6g7gn9maj.apps.googleusercontent.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_kJVAog5QNkBdHS4kz3chDwfMzMHpyY',
    appId: '1:650287500996:ios:f6f410520e23e4cc280391',
    messagingSenderId: '650287500996',
    projectId: 'test-230e1',
    storageBucket: 'test-230e1.appspot.com',
    iosClientId: '650287500996-71dua6tvem16dg95fplmv96lqmtftmma.apps.googleusercontent.com',
    iosBundleId: 'com.example.travel.RunnerTests',
  );
}
