// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdocV97zunErGvM4DEQcWrbZu66vTZk-A',
    appId: '1:110756258317:web:74167f6509c0d536a22b44',
    messagingSenderId: '110756258317',
    projectId: 'discover-86019',
    authDomain: 'discover-86019.firebaseapp.com',
    storageBucket: 'discover-86019.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWfEuiPqfXZoVJB_z3UChKeyqK_ou6SMc',
    appId: '1:110756258317:android:9d5095d34fd3602ea22b44',
    messagingSenderId: '110756258317',
    projectId: 'discover-86019',
    storageBucket: 'discover-86019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyo-zbEFzmcD-FqBuTQx-q2feYsWFd0zs',
    appId: '1:110756258317:ios:60679d4c14b9dad6a22b44',
    messagingSenderId: '110756258317',
    projectId: 'discover-86019',
    storageBucket: 'discover-86019.appspot.com',
    iosClientId: '110756258317-7p1586ea3k28f6ch4jfejj4q3po4vd7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyo-zbEFzmcD-FqBuTQx-q2feYsWFd0zs',
    appId: '1:110756258317:ios:8a450cd5ad86fa3aa22b44',
    messagingSenderId: '110756258317',
    projectId: 'discover-86019',
    storageBucket: 'discover-86019.appspot.com',
    iosClientId: '110756258317-57adcqvmoiqv6tun4nrroff1eeebk0gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.travel.RunnerTests',
  );
}
